# to use orbs, must use version >= 2.1
version: 2.1

environment:
  TERM: 'xterm'

parameters:
  TEST_BRANCH:
    type: string
    default: 'feature-X'

jobs:
  test:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: print variables
          # https://github.com/bahmutov/print-env
          # https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
          command: npx @bahmutov/print-env CIRCLE
      - run:
          name: print current branch
          command: |
            echo "current branch is: $(git branch --show-current)"
            echo "all available branches"
            git branch -a

      - run:
          name: Checkout test branch
          command: |
            echo "Switching to branch << pipeline.parameters.TEST_BRANCH >> if it exists"
            git checkout << pipeline.parameters.TEST_BRANCH >> || true
            git pull

      - run:
          name: Print current Git info
          command: |
            echo "current branch is: $(git branch --show-current)"
            echo "current commit is: $(git rev-parse --short HEAD)"

workflows:
  e2e:
    jobs:
      - test
