# to use orbs, must use version >= 2.1
version: 2.1

orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x using "@1" syntax
  cypress: cypress-io/cypress@1

environment:
  TERM: 'xterm'

parameters:
  # by default test everything using the current default branch
  # but if the pipeline is triggered via API, you can pass the branch name
  # to check out and run tests from.
  TEST_BRANCH:
    type: string
    default: 'test-feature-Y'

# https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands
commands:
  switch_branch:
    description: |
      Changes the current branch to the latest commit on the specific branch.
      NOTE: if the branch does not exist, does nothing.
    parameters:
      BRANCH_NAME:
        type: string
        default: ''
    steps:
      - when:
          condition: << parameters.BRANCH_NAME >>
          steps:
          - run:
              name: Checkout branch << parameters.BRANCH_NAME >>
              command: |
                echo "Switching to branch << parameters.BRANCH_NAME >> if it exists"
                git checkout << parameters.BRANCH_NAME >> || true
                git pull origin << parameters.BRANCH_NAME >> || true
  print_git:
    description: |
      Prints the current git branch and the commit hash.
    steps:
      - run:
          name: Print current Git info
          # looks like Cypress default executor does not have
          # a very recent Git version, thus we cannot use "--show-current"
          command: |
            echo "current branch is: $(git branch -a)"
            echo "current commit is: $(git rev-parse --short HEAD)"

jobs:
  test:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: print variables
          # https://github.com/bahmutov/print-env
          # https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
          command: npx @bahmutov/print-env CIRCLE
      - run:
          name: print current branch
          command: |
            echo "current branch is: $(git branch --show-current)"
            echo "all available branches"
            git branch -a

      - switch_branch:
          BRANCH_NAME: << pipeline.parameters.TEST_BRANCH >>

      - print_git

workflows:
  e2e:
    jobs:
      - test

      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      # see orb use examples in
      # https://github.com/cypress-io/circleci-orb#examples
      - cypress/run:
          name: Cypress E2E tests
          # switch to the test branch before installing and running tests
          post-checkout:
            - switch_branch:
                BRANCH_NAME: << pipeline.parameters.TEST_BRANCH >>
            - print_git
          # we do not need to keep the workspace around
          # since there are no other jobs that depend on it
          no-workspace: true
